apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app-nodeport-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32076
  selector:
    app: web-app
  type: NodePort

