# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import contest_pb2 as contest__pb2


class ContestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateTask = channel.unary_unary(
                '/Contest/UpdateTask',
                request_serializer=contest__pb2.UpdateMessage.SerializeToString,
                response_deserializer=contest__pb2.UpdateResponse.FromString,
                )
        self.HandleEvent = channel.unary_unary(
                '/Contest/HandleEvent',
                request_serializer=contest__pb2.EventData.SerializeToString,
                response_deserializer=contest__pb2.UpdateResponse.FromString,
                )


class ContestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=contest__pb2.UpdateMessage.FromString,
                    response_serializer=contest__pb2.UpdateResponse.SerializeToString,
            ),
            'HandleEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleEvent,
                    request_deserializer=contest__pb2.EventData.FromString,
                    response_serializer=contest__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Contest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Contest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Contest/UpdateTask',
            contest__pb2.UpdateMessage.SerializeToString,
            contest__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HandleEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Contest/HandleEvent',
            contest__pb2.EventData.SerializeToString,
            contest__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
