# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contest.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontest.proto\"4\n\rUpdateMessage\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x15\n\rsubmission_id\x18\x02 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07\x63hanged\x18\x01 \x01(\x08\"K\n\x0fGoToTimeMessage\x12\x12\n\ncontest_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\"c\n\tEventData\x12\x12\n\ncontest_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x0e\n\x06\x63\x61ller\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t2\x93\x01\n\x07\x43ontest\x12-\n\nUpdateTask\x12\x0e.UpdateMessage\x1a\x0f.UpdateResponse\x12*\n\x0bHandleEvent\x12\n.EventData\x1a\x0f.UpdateResponse\x12-\n\x08GoToTime\x12\x10.GoToTimeMessage\x1a\x0f.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATEMESSAGE']._serialized_start=17
  _globals['_UPDATEMESSAGE']._serialized_end=69
  _globals['_UPDATERESPONSE']._serialized_start=71
  _globals['_UPDATERESPONSE']._serialized_end=104
  _globals['_GOTOTIMEMESSAGE']._serialized_start=106
  _globals['_GOTOTIMEMESSAGE']._serialized_end=181
  _globals['_EVENTDATA']._serialized_start=183
  _globals['_EVENTDATA']._serialized_end=282
  _globals['_CONTEST']._serialized_start=285
  _globals['_CONTEST']._serialized_end=432
# @@protoc_insertion_point(module_scope)
