# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contest.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontest.proto\",\n\x0fSaveDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\" \n\x11RemoveDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0f\x46indDataMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x17\n\x15GetFingerTableMessage\"D\n\x10SaveDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x14\n\x07node_id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x42\n\n\x08_node_id\"5\n\x12RemoveDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\"1\n\x10\x46indDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\x05\")\n\x11GetFingerResponse\x12\x14\n\x0c\x66inger_table\x18\x01 \x03(\x05\x32\xe5\x01\n\x05\x43hord\x12\x31\n\x08SaveData\x12\x10.SaveDataMessage\x1a\x11.SaveDataResponse\"\x00\x12\x37\n\nRemoveData\x12\x12.RemoveDataMessage\x1a\x13.RemoveDataResponse\"\x00\x12\x31\n\x08\x46indData\x12\x10.FindDataMessage\x1a\x11.FindDataResponse\"\x00\x12=\n\rGetFingerData\x12\x16.GetFingerTableMessage\x1a\x12.GetFingerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SAVEDATAMESSAGE']._serialized_start=17
  _globals['_SAVEDATAMESSAGE']._serialized_end=61
  _globals['_REMOVEDATAMESSAGE']._serialized_start=63
  _globals['_REMOVEDATAMESSAGE']._serialized_end=95
  _globals['_FINDDATAMESSAGE']._serialized_start=97
  _globals['_FINDDATAMESSAGE']._serialized_end=127
  _globals['_GETFINGERTABLEMESSAGE']._serialized_start=129
  _globals['_GETFINGERTABLEMESSAGE']._serialized_end=152
  _globals['_SAVEDATARESPONSE']._serialized_start=154
  _globals['_SAVEDATARESPONSE']._serialized_end=222
  _globals['_REMOVEDATARESPONSE']._serialized_start=224
  _globals['_REMOVEDATARESPONSE']._serialized_end=277
  _globals['_FINDDATARESPONSE']._serialized_start=279
  _globals['_FINDDATARESPONSE']._serialized_end=328
  _globals['_GETFINGERRESPONSE']._serialized_start=330
  _globals['_GETFINGERRESPONSE']._serialized_end=371
  _globals['_CHORD']._serialized_start=374
  _globals['_CHORD']._serialized_end=603
# @@protoc_insertion_point(module_scope)
