apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest
  labels:
    app: contest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest
  template:
    metadata:
      labels:
        app: contest
    spec:
      containers:
      - name: contest
        image: contest
        imagePullPolicy: Never
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password

