apiVersion: batch/v1
kind: Job
metadata:
  name: init-database
spec:
  template:
    spec:
      containers:
      - name: init-database
        imagePullPolicy: Never
        image: init_database:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
      restartPolicy: Never
  backoffLimit: 4
