apiVersion: batch/v1
kind: Job
metadata:
  name: init-database
spec:
  template:
    spec:
      containers:
      - name: init-database
        imagePullPolicy: Never
        image: init_database:latest
      restartPolicy: Never
  backoffLimit: 4
