apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
  labels:
    app: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
      - name: judge
        image: judge
        imagePullPolicy: Never
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
