apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
  labels:
    app: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
      - name: judge
        image: judge
        imagePullPolicy: Never

